title: Guide OpenMower Mowgli
description: Guide complet pour configurer OpenMower avec Mowgli et Yardforce 500B
theme: just-the-docs

url: "https://juditech3d.github.io"
baseurl: "/Guide-DIY-OpenMower-Mowgli-pour-Robots-Tondeuses-Yard500-et-500B"

aux_links:
  Template Repository: https://github.com/juditech3D/Guide-DIY-OpenMower
