title: OpenMower Mowgli
description: Guide complet pour configurer OpenMower avec Mowgli et Yardforce 500B
theme: just-the-docs

url: "https://juditech3d.github.io"
baseurl: "/Guide-DIY-OpenMower-Mowgli-pour-Robots-Tondeuses-Yard500-et-500B"

aux_links:
  Template Repository: https://github.com/juditech3D/Guide-DIY-OpenMower

favicon_ico: "/favicon.ico"

just_the_docs:
  show_toc: true
  toc_levels: 1..3
  toc_sticky: true
  color_scheme_toggle: false
  color_scheme: "dark"
  nav_width: 300
  custom_css:
    - "assets/css/overrides.css"  # ✅ Corrigé ici

collections:
  pages:
    output: true
    permalink: /:path/
